### ISSUE TITLE
Check compatibility to Remoting Security Workaround

### ISSUE THREAD

**Issue by TT-S3-D1** [jenkinsci/ecutest-plugin#372]
**Describe the feature request**
Check that there is no difference in the ECU-TEST execution with and without the new plugin is installed.

**Additional context**
[Remoting Security Workaround](https://plugins.jenkins.io/remoting-security-workaround/#dependencies)

**Comment by thardtke-tt** [comment]
- Plugin Tests passed for 2.249.1 / 2.303.2 / 2.319.1
  - licence check / Package / Project / test folder / Start / Stopp / Toolserver Start / Toolserver Stopp

**Comment by TT-S3-D1** [comment]
* Compatibility already exists
* Nothing else to do here
