### ISSUE TITLE
 Provide 3rd party license check and sbom

### ISSUE THREAD

**Issue by MartinGroscheTT** [jenkinsci/ecutest-plugin#445]
**Describe the feature request**
 Fulfillment of the requirements in the section of 3rd party licenses.

**Upstream changes**
* [ ] sbom is available for every version
* [ ] provide allowlist
* [ ] all licenses are checked against allowlist
* [ ] README for usage of sbom

**Comment by TT-S3-D1** [comment]
rejected - see #572
