### ISSUE TITLE
got a eccror "Caught ComException: Can't map name to dispid: GetState"

### ISSUE THREAD

**Issue by rionazhang** [jenkinsci/ecutest-plugin#449]
got a eccror "Caught ComException: Can't map name to dispid: GetState" when we we use ecu-test to execute halfway with jenkins

**Jenkins log:**
[TT] INFO: -- tick...
[TT] INFO: -- tick...
[TT] ERROR: Caught ComException: Can't map name to dispid: GetState
For further information see FAQ: https://github.com/jenkinsci/ecutest-plugin#faq
Enable debug mode for fine-grained logs: https://github.com/jenkinsci/ecutest-plugin#debugging
[TT] ERROR: Executing project failed!
[TT] INFO: - Closing running ECU-TEST and Tool-Server instances...

**Comment by TT-S3-D1** [comment]
Hello @rionazhang 
does this issue still exist? Seems to be something sporadic with a frozen or closed ECU-TEST.
Do you need help here?

Best Regards
Sebastian

**Comment by TT-S3-D1** [comment]
rejected - no answer
