### ISSUE TITLE
Remove Java 8 Support

### ISSUE THREAD

**Issue by TT-S3-D1** [jenkinsci/ecutest-plugin#498]
**Describe the feature request**
As a plugin maintainer I want to support newer LTS versions and need therefore Java 17 support - Java 8 has to be removed.

**Upstream changes**
* Change build version from Java 8 to Java 11
* Update README

**Additional context**
* Java 11 is the minimum version for Jenkins 2.361

**Comment by cwellmtt** [comment]
Please note the bug in IntelliJ:
https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.40
