### ISSUE TITLE
Provide published links for downstream steps

### ISSUE THREAD

**Issue by S3-D1** [jenkinsci/ecutest-plugin#79]
After #24 the report links are not usable for downstream steps because of the random id. to provide these links users need a solution (provide the link or the id or ...)

**Comment by cpoenisch** [comment]
The id of each generated report (regardless of downstream execution) can be resolved by iterating the according build action.

Example accessing ATX report IDs and redirecting URL from inside pipeline:
```
def action = currentBuild.rawBuild.getAction(de.tracetronic.jenkins.plugins.ecutest.report.atx.ATXBuildAction.class)

def reports = action?.getATXReports()
reports.each { report ->
	println report.getId() // random id
	println report.getReportUrl() // filter link to TEST-GUIDE
}
```
