### ISSUE TITLE
Migrate the plugin documentation from Wiki to GitHub

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/ecutest-plugin#87]
We have recently introduced support of GitHub documentation on the Jenkins Plugin Site. See [this Developer thread](https://groups.google.com/forum/#!topic/jenkinsci-dev/VSdfVMDIW-A) for the announcement. 

Jenkins users seeking documentation will have a better user experience on [plugins.jenkins.io](https://plugins.jenkins.io/) than they do on wiki.jenkins.io. At the same time, maintainers can follow the documentation-as-code approach and make documentation changes a part of pull requests. Documentation changes will be reviewed as part of pull requests and documentation contributors will be recognized, especially when combined with Release Drafter. We recommend all plugins to migrate documentation to GitHub.

Once documentation is moved, the plugin metadata needs to be updated to point to GitHub: documentation URL in the project file ([guide]( https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Referencingthedocumentationpagefromtheprojectfile)) . Then the change will be applied after the release.

P.S: In Jenkins project we track the documentation migration as one of the Hacktoberfest featured project: https://jenkins.io/events/hacktoberfest/ . Please feel free to put a Hacktoberfest label in this repo if you are interested to suggest it for external contributions

**Comment by cpoenisch** [comment]
Move wiki attachment to GitHub: [swarm-client-jar-with-dependencies.zip](https://github.com/jenkinsci/ecutest-plugin/files/3743523/swarm-client-jar-with-dependencies.zip)
